# Generated by Django 4.1.7 on 2023-02-21 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api5', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageSlider',
            fields=[
                ('ImageSlider_id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='')),
                ('about', models.TextField()),
                ('added_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
