# Generated by Django 4.1.7 on 2023-02-23 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api5', '0004_alter_quicklinks_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Objectives_of_Sikkim_University',
            fields=[
                ('Objectives_of_Sikkim_University_id', models.AutoField(primary_key=True, serialize=False)),
                ('objective', models.TextField()),
                ('added_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
