# Generated by Django 4.1.7 on 2023-03-01 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api5', '0005_objectives_of_sikkim_university'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upcoming_Events',
            fields=[
                ('Upcoming_Events_id', models.AutoField(primary_key=True, serialize=False)),
                ('link', models.TextField()),
                ('text', models.TextField()),
            ],
        ),
    ]
