# Generated by Django 4.1.7 on 2023-03-03 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api5', '0006_upcoming_events'),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('School_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('Department_id', models.AutoField(primary_key=True, serialize=False)),
                ('Department_name', models.CharField(max_length=50)),
                ('School_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api5.school')),
            ],
        ),
    ]
